services:
  turnierplaner:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: hajozi70/turnierplaner:${VERSION:-latest}
    container_name: turnierplaner
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    #devices:
    #  - "/dev/snd:/dev/snd"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health',(res)=>process.exit(res.statusCode===200?0:1)).on('error',()=>process.exit(1));",
        ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  turnierplaner-timer-php:
    build:
      context: .
      dockerfile: Dockerfile.timer
    image: hajozi70/turnierplaner-timer-php:${VERSION:-latest}
    container_name: turnierplaner-timer-php
    ports:
      - "8080:80"
    volumes:
      - ./Timer/sounds:/var/www/html/sounds:ro
    restart: unless-stopped
    environment:
      TURNIERPLANER_API_BASE_URL: ${TURNIERPLANER_API_BASE_URL:-https://otticup.akzimmer.de}
      TURNIERPLANER_INTERNAL_API_BASE_URL: ${TURNIERPLANER_INTERNAL_API_BASE_URL:-https://otticup.akzimmer.de}